version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_SERVICE_ID=${PUBLIC_SERVICE_ID:-}
        - PUBLIC_TEMPLATE_ID=${PUBLIC_TEMPLATE_ID:-}
        - PUBLIC_EMAILJS_KEY=${PUBLIC_EMAILJS_KEY:-}
    env_file:
      - .env
    container_name: alexyvanot-portfolio
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nginx_logs: